// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BlazorApp1.Models;

public partial class DapperDBContext : DbContext
{
    public DapperDBContext(DbContextOptions<DapperDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<Skill> Skills { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasKey(e => e.Empid);

            entity.ToTable("Employee");

            entity.Property(e => e.Empid).HasColumnName("EMPID");
            entity.Property(e => e.EmpAge).HasColumnName("EMP_AGE");
            entity.Property(e => e.EmpDesignation)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("EMP_DESIGNATION");
            entity.Property(e => e.EmpEmail)
                .HasMaxLength(100)
                .HasColumnName("EMP_EMAIL");
            entity.Property(e => e.EmpGender)
                .HasMaxLength(10)
                .HasColumnName("EMP_GENDER");
            entity.Property(e => e.EmpSalary).HasColumnName("EMP_SALARY");
            entity.Property(e => e.EmpSkills).HasColumnName("EMP_SKILLS");
            entity.Property(e => e.Empname)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("EMPNAME");
            entity.Property(e => e.IsDeleted).HasDefaultValueSql("((0))");

            entity.HasMany(d => d.Skills).WithMany(p => p.Emps)
                .UsingEntity<Dictionary<string, object>>(
                    "EmployeeSkill",
                    r => r.HasOne<Skill>().WithMany()
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__EmployeeS__Skill__4CA06362"),
                    l => l.HasOne<Employee>().WithMany()
                        .HasForeignKey("Empid")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__EmployeeS__EMPID__4BAC3F29"),
                    j =>
                    {
                        j.HasKey("Empid", "SkillId").HasName("PK__Employee__7936D06388FD431C");
                        j.ToTable("EmployeeSkill");
                        j.IndexerProperty<int>("Empid").HasColumnName("EMPID");
                        j.IndexerProperty<int>("SkillId").HasColumnName("SkillID");
                    });
        });

        modelBuilder.Entity<Skill>(entity =>
        {
            entity.HasKey(e => e.SkillId).HasName("PK__Skill__DFA0918797435711");

            entity.ToTable("Skill");

            entity.Property(e => e.SkillName)
                .IsRequired()
                .HasMaxLength(255);
        });

        OnModelCreatingGeneratedProcedures(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}