// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorApp1.Models;

public partial class Employee
{
    public int Empid { get; set; }

    public string Empname { get; set; }

    public string EmpDesignation { get; set; }

    public int? EmpSalary { get; set; }

    public bool? IsDeleted { get; set; }

    public string EmpGender { get; set; }

    public string EmpEmail { get; set; }

    public int? EmpAge { get; set; }

    public string EmpSkills { get; set; }

    public virtual ICollection<Skill> Skills { get; set; } = new List<Skill>();
}