// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace BlazorApp1.Models
{
    public partial class GetAllDeletedEmployeesResult
    {
        public int EMPID { get; set; }
        public string EMPNAME { get; set; }
        public string EMP_DESIGNATION { get; set; }
        public int? EMP_SALARY { get; set; }
        public bool? IsDeleted { get; set; }
        public string EMP_GENDER { get; set; }
        public string EMP_EMAIL { get; set; }
        public int? EMP_AGE { get; set; }
        public string EMP_SKILLS { get; set; }
    }
}
